DROP TABLE Doctors;

CREATE TABLE Doctors (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  phone VARCHAR2(100),
  email VARCHAR2(255),
  title VARCHAR2(255) NOT NULL
);

INSERT INTO Doctors (id,name,phone,email,title) VALUES (1,'Mannix Golden','375337201403','Pellentesque.ultricies@mi.org','офтальмолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (2,'Grant English','375331483129','Cras.interdum@magnaPraesent.ca','офтальмолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (3,'Tobias Rogers','375446888987','mattis.Cras.eget@velmauris.org','инфекционист');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (4,'Wylie Stevenson','375251678484','ornare@volutpatnuncsit.ca','инфекционист');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (5,'Beau Nguyen','375293562181','sapien@Pellentesque.ca','офтальмолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (6,'Channing Carrillo','375292405578','libero.nec@dolorQuisquetincidunt.edu','инфекционист');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (7,'Geoffrey Jenkins','375331655759','laoreet.ipsum.Curabitur@Duiselementumdui.edu','педиатр');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (8,'Allen Nichols','375333322248','neque.In@sodalespurus.ca','педиатр');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (9,'Wylie Farley','375253284706','tortor@laoreet.co.uk','диетолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (10,'Otto Huffman','375443469083','sed.facilisis.vitae@elita.co.uk','акушер-гинеколог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (11,'Rogan Rosario','375338465927','mattis.Cras@montesnascetur.edu','педиатр');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (12,'Silas Ortiz','375442677398','pede.Praesent.eu@nisi.edu','акушер-гинеколог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (13,'Allistair Solomon','375251054038','dignissim.tempor@per.ca','педиатр');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (14,'Wylie Marks','375291892097','nulla.vulputate.dui@purusaccumsan.com','кардиолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (15,'August Jefferson','375339507603','consectetuer.euismod.est@Integer.ca','диетолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (16,'Reed Wyatt','375296526894','sem.eget.massa@sitametrisus.net','инфекционист');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (17,'Sebastian Jarvis','375447623944','Nulla@euismodacfermentum.ca','акушер-гинеколог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (18,'Oleg King','375253356423','Ut@nisiCum.org','инфекционист');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (19,'Buckminster Blair','375290781065','Cras@aliquamenimnec.com','терапевт');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (20,'Tyrone Lopez','375444255456','metus.facilisis@lectus.net','диетолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (21,'Joel Velazquez','375295573237','sed.facilisis@enim.net','онколог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (22,'Gil Richardson','375257100536','per@nislQuisque.com','акушер-гинеколог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (23,'Evan Shields','375339763557','diam.Pellentesque.habitant@eratvitaerisus.edu','офтальмолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (24,'Arsenio Tanner','375255621323','luctus.vulputate@ornareelit.edu','акушер-гинеколог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (25,'Emery Murphy','375336774087','sit.amet.ultricies@interdum.net','диетолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (26,'Orlando Cobb','375448399590','molestie.dapibus@liberomaurisaliquam.co.uk','диетолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (27,'Malachi Carter','375440436133','malesuada.ut.sem@suscipitest.net','диетолог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (28,'Jarrod Bridges','375295240559','pede.nonummy@malesuadamalesuadaInteger.co.uk','педиатр');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (29,'Carl Rowland','375334637830','sagittis@Inornare.co.uk','акушер-гинеколог');
INSERT INTO Doctors (id,name,phone,email,title) VALUES (30,'Keegan Wong','375292572492','facilisis.magna@ullamcorpermagnaSed.org','акушер-гинеколог');