DROP TABLE Patients;

CREATE TABLE Patients (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  phone VARCHAR2(100),
  email VARCHAR2(255),
  birth_date VARCHAR2(19) NOT NULL,
  address VARCHAR2(255) NOT NULL,
  gender VARCHAR2(15) NOT NULL
);

INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (1,'Jakeem','375291841270','sem@egettinciduntdui.net','31/12/1969','925-2367 Vestibulum Rd.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (2,'Tatiana','375257192388','felis@tortordictumeu.org','31/12/1969','3921 Dui, Road','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (3,'Alden','375295668717','ullamcorper.viverra.Maecenas@idblanditat.org','31/12/1969','3806 Duis Rd.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (4,'Ramona','375258846175','fringilla@sedpedeCum.net','31/12/1969','P.O. Box 859, 8455 Sed Av.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (5,'Cynthia','375442275511','Praesent.luctus@semegestasblandit.edu','31/12/1969','371-8800 Ut, Av.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (6,'Robin','375256290760','elit.elit.fermentum@massa.edu','31/12/1969','P.O. Box 492, 6076 Leo. Rd.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (7,'Otto','375257818013','bibendum@Nullamvelitdui.ca','31/12/1969','9843 Fringilla Avenue','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (8,'Zeus','375290470211','orci.in@Nullamut.com','31/12/1969','3112 Id Rd.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (9,'Brennan','375258306604','est.vitae@vulputatedui.com','31/12/1969','Ap #360-9682 Eget St.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (10,'Colton','375294444524','augue@Donecfringilla.co.uk','31/12/1969','Ap #698-3656 Quis Street','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (11,'Hashim','375292697659','Donec.luctus@elitpretium.com','31/12/1969','Ap #950-5521 Vel Av.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (12,'Herman','375259964534','vulputate.nisi.sem@nullaInteger.org','31/12/1969','Ap #325-3202 Aliquam St.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (13,'Amal','375258948464','magna.et@magnaPhasellus.org','31/12/1969','P.O. Box 487, 1225 Commodo Rd.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (14,'Brian','375297877539','Nam@enimmi.ca','31/12/1969','P.O. Box 444, 5375 A St.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (15,'Josiah','375447832185','nonummy.Fusce.fermentum@convallisdolorQuisque.edu','31/12/1969','Ap #903-3261 Non Ave','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (16,'Helen','375256104003','lectus.Nullam.suscipit@ligulaNullam.net','31/12/1969','Ap #297-2135 Risus. Rd.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (17,'Urielle','375442545140','sit.amet.ornare@suscipitnonummyFusce.net','31/12/1969','P.O. Box 192, 1343 Dolor. Rd.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (18,'Kirk','375445440395','aliquam.enim.nec@justonec.co.uk','31/12/1969','5311 Tortor. Ave','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (19,'Demetria','375256606353','ante.iaculis@acmi.edu','31/12/1969','566-1417 Semper Rd.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (20,'Sebastian','375443135979','eu.ultrices.sit@Class.ca','31/12/1969','6910 Sit Av.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (21,'Jarrod','375447657646','vitae.odio.sagittis@amagna.co.uk','31/12/1969','P.O. Box 891, 6277 Sed St.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (22,'Teegan','375290484274','tristique.aliquet@Quisquetinciduntpede.ca','31/12/1969','2400 Amet Road','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (23,'Fuller','375257213752','volutpat.nunc.sit@Vivamusnon.net','31/12/1969','P.O. Box 498, 7202 Ipsum Avenue','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (24,'Leilani','375252719576','non@Etiamimperdietdictum.co.uk','31/12/1969','Ap #950-6202 Ac Avenue','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (25,'Rebecca','375291121448','commodo.hendrerit.Donec@tempor.ca','31/12/1969','399-7476 Etiam Ave','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (26,'Dean','375297471443','nulla.Integer.vulputate@Aliquamrutrumlorem.edu','31/12/1969','278-3156 Eu Av.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (27,'Upton','375296387869','ultrices.sit@elit.com','31/12/1969','Ap #862-7829 Ridiculus Rd.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (28,'Kylie','375442204166','vitae@nostra.org','31/12/1969','2635 Penatibus Avenue','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (29,'Harper','375293536294','varius@posuerecubiliaCurae.com','31/12/1969','452-5870 Rutrum Road','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (30,'Chadwick','375449814008','ipsum.primis@rhoncusDonecest.co.uk','31/12/1969','250-3271 Eget Road','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (31,'Sydnee','375442237806','mauris@quis.edu','31/12/1969','835-493 Erat Rd.','w');