DROP TABLE Patients;

CREATE TABLE Patients (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  phone VARCHAR2(100),
  email VARCHAR2(255),
  birth_date VARCHAR2(19) NOT NULL,
  address VARCHAR2(255) NOT NULL,
  gender VARCHAR2(15) NOT NULL
);

INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (1,'Sade','375444061239','luctus@ametrisus.edu','07/09/1956','P.O. Box 511, 9300 Nullam Road','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (2,'Alexander','375294587796','Pellentesque@aliquam.edu','30/07/1968','Ap #404-6222 Rutrum Street','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (3,'Vaughan','375443109867','quis.diam@blanditviverraDonec.edu','25/02/1974','169-4304 Ac Avenue','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (4,'Guy','375291570614','magna.Lorem@enimSuspendisse.com','02/05/1982','Ap #104-4788 Non Avenue','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (5,'Kevyn','375291479431','massa.Suspendisse@amalesuada.edu','24/02/1984','7547 Ac Road','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (6,'Orla','375296650030','egestas.rhoncus.Proin@ipsum.ca','24/03/1959','Ap #432-5088 Amet, St.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (7,'Nadine','375298057979','sem@auctorvitae.ca','18/04/1997','Ap #779-8409 Gravida Ave','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (8,'Tad','375291910328','augue.porttitor.interdum@eu.com','14/02/1978','Ap #491-1005 Nisi Road','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (9,'Price','375443884356','adipiscing.elit.Etiam@adipiscinglacusUt.co.uk','15/09/1994','787-9243 Vehicula. Ave','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (10,'Wanda','375291892097','Cras.interdum.Nunc@antedictumcursus.ca','11/02/1981','363-5080 Mauris St.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (11,'Leigh','375442005446','enim.diam@metusvitae.com','28/05/1968','2259 Pharetra Rd.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (12,'Byron','375446536652','Mauris@Donecnibh.org','21/04/1993','893-7394 Lectus Ave','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (13,'Vernon','375251149355','Proin@auctorMaurisvel.net','19/01/2006','745-3958 Id, Road','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (14,'Duncan','375295006986','elementum.sem.vitae@pedeacurna.com','28/07/1961','2349 Nonummy St.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (15,'Bruce','375449692560','et.malesuada@id.co.uk','23/08/1992','Ap #315-3799 Mus. Ave','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (16,'Baker','375255650118','fringilla@luctusut.com','29/10/1979','434 Varius. Road','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (17,'Hillary','375447837990','nec.urna.et@nisl.net','18/12/1949','Ap #440-8484 Orci Road','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (18,'Byron','375448347327','dictum.eu.eleifend@loremsit.edu','22/06/1961','5831 Nisl. St.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (19,'Mohammad','375259206405','eu.dui@anteipsumprimis.net','17/05/1966','275-3417 Molestie Avenue','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (20,'Xaviera','375299608725','arcu.Vivamus@FuscemollisDuis.org','06/10/1973','Ap #238-7452 Consectetuer Street','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (21,'Amber','375291755206','risus.Nunc.ac@NulladignissimMaecenas.org','13/08/1998','Ap #338-7713 Euismod Rd.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (22,'Cody','375443498277','elit.Etiam@nibh.co.uk','11/06/1985','758-7093 Et, Av.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (23,'Orli','375297134086','vehicula@augueporttitor.ca','24/01/1971','Ap #946-9652 Nunc Street','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (24,'Remedios','375258213403','commodo.ipsum@et.com','20/08/1990','811-1405 Neque. St.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (25,'Bruce','375258979258','ultrices@neceuismod.com','04/05/1983','P.O. Box 674, 4160 Vitae, Rd.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (26,'Honorato','375258260704','mus@idrisusquis.ca','31/12/1962','779-297 Dignissim. Ave','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (27,'Louis','375252586845','Integer.vulputate@magna.com','25/02/2002','6694 Nibh Rd.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (28,'Oren','375443459174','id.libero.Donec@erosProin.com','19/12/1954','Ap #713-6697 Arcu St.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (29,'Keefe','375295072928','Pellentesque@elitpede.net','25/12/1996','5781 Erat St.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (30,'Bree','375449799834','quam.elementum@nonjustoProin.edu','22/10/1951','P.O. Box 565, 5255 Elit. St.','w');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (31,'Levi','375448351472','nunc.interdum.feugiat@Aliquamgravida.org','07/03/2005','493-3796 Adipiscing. St.','m');
INSERT INTO Patients (id,name,phone,email,birth_date,address,gender) VALUES (32,'Jameson','375444473145','nunc@Etiam.ca','15/07/1989','Ap #806-9948 Ultricies Rd.','m');