CREATE USER ALEX IDENTIFIED BY ADMIN DEFAULT TABLESPACE USERS

GRANT CONNECT, RESOURCE, DBA TO ALEX;

GRANT CREATE SESSION TO ALEX
/
GRANT CREATE TABLE TO ALEX
/
GRANT CREATE PROCEDURE TO ALEX
/
GRANT CREATE TRIGGER TO ALEX
/
GRANT CREATE VIEW TO ALEX
/
GRANT CREATE SEQUENCE TO ALEX
/
GRANT CREATE VIEW TO ALEX
/

GRANT DELETE ANY TABLE TO ALEX
/
GRANT DROP ANY TABLE TO ALEX
/
GRANT DROP ANY PROCEDURE TO ALEX
/
GRANT DROP ANY TRIGGER TO ALEX
/
GRANT DROP ANY VIEW TO ALEX
/

GRANT ALTER ANY TABLE TO ALEX
/
GRANT ALTER ANY TABLE TO ALEX
/
GRANT ALTER ANY PROCEDURE TO ALEX
/
GRANT ALTER ANY TRIGGER TO ALEX

COMMIT
/