CREATE TABLE Visits (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  temperature NUMBER NOT NULL,
  bed_id NUMBER NOT NULL,
  discharge_date VARCHAR2(19) NOT NULL,
  visit_date VARCHAR2(19) NOT NULL,
  FOREIGN KEY (patient_id) REFERENCES Patients(id),
  FOREIGN KEY (doctor_id) REFERENCES Doctors(id),
  FOREIGN KEY (bed_id) REFERENCES Hospital_Beds(id)
);

INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (1,18,15,64,'02/06/2021','11/05/2021',38.3);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (2,17,17,46,'31/05/2021','04/05/2021',38.6);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (3,30,7,74,'05/06/2021','01/05/2021',39.4);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (4,22,18,12,'30/05/2021','06/05/2021',37.3);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (5,21,10,43,'02/06/2021','18/05/2021',37.7);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (6,13,16,5,'09/06/2021','23/05/2021',37.9);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (7,6,12,58,'02/06/2021','22/05/2021',37.8);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (8,14,11,62,'01/06/2021','01/05/2021',39.6);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (9,28,20,47,'29/05/2021','15/05/2021',39.5);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (10,27,12,21,'09/06/2021','15/05/2021',39.6);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (11,6,16,48,'04/06/2021','07/05/2021',38.5);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (12,26,15,17,'28/05/2021','24/05/2021',38.8);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (13,4,14,41,'03/06/2021','06/05/2021',39.4);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (14,14,24,41,'30/05/2021','10/05/2021',38.5);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (15,19,13,35,'08/06/2021','03/05/2021',38.6);
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (16,26,30,57,'02/06/2021','13/05/2021',39.6 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (17,10,25,26,'11/06/2021','21/05/2021',38.4 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (18,16,23,8,'09/06/2021','04/05/2021',38.8 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (19,28,30,41,'29/05/2021','04/05/2021',39.9 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (20,25,8,66,'07/06/2021','06/05/2021',39.6 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (21,2,6,66,'10/06/2021','10/05/2021',37.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (22,3,23,30,'09/06/2021','11/05/2021',37.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (23,28,30,50,'06/06/2021','21/05/2021',39.2 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (24,3,14,50,'31/05/2021','23/05/2021',38.5 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (25,8,26,17,'02/06/2021','14/05/2021',39.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (26,17,21,73,'06/06/2021','04/05/2021',38.7 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (27,20,25,53,'07/06/2021','16/05/2021',37.3 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (28,6,10,17,'08/06/2021','02/05/2021',38.5 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (29,22,18,3,'05/06/2021','24/05/2021',37.4 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (30,4,1,21,'06/06/2021','13/05/2021',39.6 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (31,20,4,69,'29/05/2021','24/05/2021',37.4 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (32,16,3,50,'08/06/2021','07/05/2021',37.8 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (33,19,30,30,'30/05/2021','10/05/2021',39.9 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (34,6,9,32,'27/05/2021','09/05/2021',38.6 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (35,7,6,53,'08/06/2021','15/05/2021',39.7 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (36,2,1,23,'06/06/2021','21/05/2021',39.5 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (37,21,2,76,'11/06/2021','13/05/2021',39.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (38,2,29,74,'01/06/2021','24/05/2021',37.2 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (39,19,10,9,'04/06/2021','19/05/2021',39.3 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (40,15,7,63,'03/06/2021','12/05/2021',39.8 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (41,2,21,49,'29/05/2021','19/05/2021',39.2 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (42,15,24,45,'07/06/2021','04/05/2021',37.8 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (43,5,4,60,'04/06/2021','22/05/2021',37.5 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (44,17,23,7,'30/05/2021','07/05/2021',39.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (45,10,2,50,'05/06/2021','05/05/2021',39.3 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (46,21,14,27,'06/06/2021','08/05/2021',37.2 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (47,3,18,76,'31/05/2021','03/05/2021',39.7 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (48,21,7,72,'03/06/2021','20/05/2021',38.6 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (49,22,30,15,'03/06/2021','05/05/2021',37.7 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (50,28,17,55,'09/06/2021','18/05/2021',39.9 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (51,16,14,50,'30/05/2021','02/05/2021',38.8 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (52,19,28,19,'03/06/2021','15/05/2021',37.3 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (53,13,8,8,'11/06/2021','02/05/2021',37.2 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (54,18,7,9,'01/06/2021','04/05/2021',37.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (55,31,4,24,'05/06/2021','12/05/2021',39.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (56,25,7,7,'09/06/2021','13/05/2021',39.8 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (57,17,18,33,'06/06/2021','05/05/2021',37.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (58,8,7,9,'05/06/2021','11/05/2021',39.9 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (59,26,30,50,'10/06/2021','04/05/2021',37.2 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (60,4,17,16,'03/06/2021','11/05/2021',38.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (61,6,18,67,'28/05/2021','08/05/2021',38.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (62,25,16,75,'06/06/2021','05/05/2021',38.8 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (63,6,25,53,'06/06/2021','15/05/2021',38.3 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (64,20,26,68,'30/05/2021','24/05/2021',39.4 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (65,2,13,69,'01/06/2021','14/05/2021',38.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (66,31,21,60,'09/06/2021','10/05/2021',39.7 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (67,24,16,31,'05/06/2021','10/05/2021',38.7 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (68,2,3,65,'09/06/2021','21/05/2021',38.9 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (69,12,2,4,'01/06/2021','02/05/2021',39.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (70,7,23,64,'29/05/2021','24/05/2021',38.4 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (71,29,27,3,'09/06/2021','14/05/2021',39.2 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (72,25,19,76,'03/06/2021','04/05/2021',39.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (73,11,9,66,'08/06/2021','24/05/2021',39.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (74,14,16,43,'27/05/2021','22/05/2021',37.7 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (75,31,28,32,'05/06/2021','12/05/2021',37.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (76,8,18,58,'07/06/2021','14/05/2021',39.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (77,6,16,69,'31/05/2021','09/05/2021',39.3 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (78,14,19,33,'30/05/2021','24/05/2021',37.8 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (79,30,23,17,'10/06/2021','18/05/2021',39.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (80,4,1,44,'29/05/2021','15/05/2021',37.9 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (81,2,28,36,'08/06/2021','20/05/2021',39.2 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (82,7,5,34,'29/05/2021','14/05/2021',38.6 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (83,3,5,42,'29/05/2021','13/05/2021',39.6 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (84,13,3,73,'31/05/2021','10/05/2021',37.3 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (85,2,9,54,'07/06/2021','20/05/2021',37.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (86,28,29,35,'05/06/2021','09/05/2021',37.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (87,6,29,64,'29/05/2021','20/05/2021',37.4 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (88,6,19,70,'11/06/2021','20/05/2021',37.7 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (89,23,26,8,'03/06/2021','20/05/2021',39.6 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (90,2,5,70,'09/06/2021','17/05/2021',39.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (91,6,18,6,'03/06/2021','15/05/2021',39.1 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (92,14,22,45,'06/06/2021','17/05/2021',38.0 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (93,16,20,48,'30/05/2021','13/05/2021',39.3 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (94,18,28,53,'11/06/2021','09/05/2021',38.7 );
INSERT INTO Visits (id,patient_id,doctor_id,bed_id,discharge_date,visit_date,temperature) VALUES (95,23,24,48,'29/05/2021','22/05/2021',37.3 );