DROP TABLE Visit_Diagnoses;

CREATE TABLE Visit_Diagnoses (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diagnosis_id NUMBER,
  visit_id NUMBER NOT NULL,
  FOREIGN KEY (diagnosis_id) REFERENCES Diagnoses(id),
  FOREIGN KEY (visit_id) REFERENCES Visits(id)
);

INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (1,7,94);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (2,9,39);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (3,8,89);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (4,1,4);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (5,2,70);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (6,4,29);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (7,9,51);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (8,4,20);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (9,7,53);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (10,1,36);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (11,8,94);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (12,10,46);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (13,2,75);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (14,7,68);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (15,4,79);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (16,4,71);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (17,10,39);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (18,5,38);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (19,2,87);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (20,1,51);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (21,5,24);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (22,2,41);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (23,10,54);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (24,10,19);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (25,6,84);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (26,8,28);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (27,8,81);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (28,10,71);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (29,4,14);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (30,2,28);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (31,5,45);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (32,5,31);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (33,7,35);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (34,9,59);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (35,7,18);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (36,10,75);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (37,9,6);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (38,1,3);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (39,6,26);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (40,4,47);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (41,1,29);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (42,5,46);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (43,4,50);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (44,2,71);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (45,6,40);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (46,6,76);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (47,5,62);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (48,7,86);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (49,7,44);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (50,4,58);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (51,NULL,90);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (52,6,18);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (53,5,20);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (54,2,3);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (55,10,24);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (56,6,83);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (57,6,80);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (58,10,27);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (59,8,81);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (60,7,77);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (61,6,7);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (62,4,20);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (63,5,32);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (64,6,62);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (65,5,1);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (66,10,9);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (67,10,34);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (68,9,65);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (69,7,62);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (70,6,19);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (71,1,3);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (72,7,1);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (73,10,59);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (74,10,51);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (75,7,79);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (76,9,71);
INSERT INTO Visit_Diagnoses (id,diagnosis_id,visit_id) VALUES (77,6,34);